// The NOT NULL class.
//
// `phantom-write-columns.test.ts` catches a write that names a column the table
// does not have. This catches the opposite mistake on a column it DOES have:
// writing a value that can be `null` into a column declared NOT NULL with no
// default. Postgres rejects the whole statement, so the write does nothing at
// all, and the caller sees a 500 it has no way to explain.
//
// One was live and it was the worst-placed defect in the product:
//
//   artist_applications.primary_medium   `primary_medium: d.primaryMedium || null`
//                                        in /api/apply. The form does not mark
//                                        the medium select required, so leaving
//                                        it blank 500'd the submission and wrote
//                                        nothing. That is the first step of the
//                                        artist acquisition funnel. The same file
//                                        already had `d.primaryMedium || ""` two
//                                        hundred lines down, for the profile
//                                        bridge, which is what the column needed.
//
// The snapshot is `schema-not-null.json`, regenerated by `npm run schema:snapshot`
// alongside `schema-columns.json`. It carries only columns that are NOT NULL AND
// have no default: a NOT NULL column WITH a default is filled by Postgres when
// the key is absent, and an explicit null is still an error, so those are checked
// here too whenever the key is actually named.

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { inlineWrites, walk } from "./db-write-scan";

const SRC = path.resolve(__dirname, "../../src");
const NOT_NULL: Record<string, string[]> = JSON.parse(
  readFileSync(path.join(__dirname, "schema-not-null.json"), "utf8"),
);

/**
 * Writes that put a nullable expression into a NOT NULL column, kept
 * deliberately.
 *
 * Each entry is a claim that the expression cannot actually be null at this call
 * site (a guard above it, a schema default upstream). Shrink it, never grow it.
 */
const GRANDFATHERED: Array<{ file: string; table: string; column: string; why: string }> = [];

/**
 * Does this value expression evaluate to `null` for some input?
 *
 * Conservative on purpose. It fires on the three shapes that actually produce
 * the bug and nothing else, so a hit is a hit:
 *
 *   `null`                bare literal
 *   `x || null`           the falsy-coalesce that started this
 *   `x ?? null`           the nullish version of the same
 *
 * A call like `foo(x)` may well return null and is NOT flagged: following it
 * needs type information, and a guard that guesses gets switched off.
 */
export function writesNull(value: string): boolean {
  const v = value
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\/\/.*$/gm, "")
    .trim()
    .replace(/,$/, "")
    .trim();
  if (v === "null") return true;
  // Last operand of a `||` / `??` chain, ignoring a trailing `as T` cast.
  const tail = v.replace(/\s+as\s+[\w<>[\]|.\s]+$/, "").trim();
  return /(\|\||\?\?)\s*null$/.test(tail);
}

describe("no insert writes null into a NOT NULL column", () => {
  it("every NOT NULL column gets a non-null value", () => {
    const offences: string[] = [];
    let checked = 0;

    for (const file of walk(SRC)) {
      const rel = path.relative(SRC, file);
      const source = readFileSync(file, "utf8");
      for (const w of inlineWrites(source)) {
        // Only inserts. An `update` that sets a column to null is the same
        // error, but an update payload is routinely a partial patch built from
        // optional fields, and the scanner cannot tell "clear this" from
        // "leave it alone" without following the caller.
        if (w.op !== "insert" && w.op !== "upsert") continue;
        const required = NOT_NULL[w.table];
        if (!required) continue;
        for (const entry of w.entries) {
          if (!required.includes(entry.key)) continue;
          checked++;
          if (!writesNull(entry.value)) continue;
          if (
            GRANDFATHERED.some(
              (g) => rel.endsWith(g.file) && g.table === w.table && g.column === entry.key,
            )
          ) {
            continue;
          }
          offences.push(
            `${rel}:${w.line} ${w.op}s null into "${w.table}.${entry.key}", which is NOT NULL`,
          );
        }
      }
    }

    expect(
      offences,
      "Postgres rejects the whole statement, so the row is never written and the " +
        'caller gets an unexplained 500. Use `|| ""` (or a real default) instead of ' +
        "`|| null`, or make the column nullable in a migration and regenerate " +
        "tests/integration/schema-not-null.json.",
    ).toEqual([]);

    // The guard is worthless if the scanner stops matching. Production has ~40
    // inserts naming a NOT NULL column between them.
    expect(checked, "the scanner matched nothing; it has stopped working").toBeGreaterThan(20);
  });

  it("keeps the allowlist honest", () => {
    for (const g of GRANDFATHERED) {
      expect(g.why.length, `${g.table}.${g.column} needs a real reason`).toBeGreaterThan(40);
    }
  });
});

describe("writesNull", () => {
  it("catches the shapes that actually produce the bug", () => {
    expect(writesNull("null")).toBe(true);
    expect(writesNull(" null ,")).toBe(true);
    expect(writesNull("d.primaryMedium || null")).toBe(true);
    expect(writesNull("d.primaryMedium ?? null")).toBe(true);
    expect(writesNull("a || b || null")).toBe(true);
    expect(writesNull("(x as string | null) ?? null")).toBe(true);
  });

  it("does not fire on values that cannot be null", () => {
    expect(writesNull('d.primaryMedium || ""')).toBe(false);
    expect(writesNull("d.name")).toBe(false);
    expect(writesNull("nullableHelper(x)")).toBe(false);
    expect(writesNull('"nullify"')).toBe(false);
    expect(writesNull("null_count")).toBe(false);
  });
});
